### ISSUE TITLE
Datasets path modification

### ISSUE THREAD

**Issue by agoyang** [JiuhaiChen/EBBS#1]
After unzipping the datasets.zip,

 `python run.py --datasets house --task regression --X_lam 20.0 --X_step 5 --y_lam 2.0 --y_step 5 --lr 0.1 --label_smooth --error_smooth `

will show a FileNotFoundError.

Since run.py and the datasets folder will be in a same parent directory, maybe it's better to change this?

https://github.com/JiuhaiChen/EBBS/blob/0b808f9746407abecda12c394f2e11cc3238d14d/run.py#L92

into
`input_folder = Path(__file__).parent / "datasets" / data_name`

**Comment by JiuhaiChen** [comment]
Hi, sorry about the confusion. We still need to clean out the code, the
version you found is not ready. I will let you know asap when the code is
ready.

Best,
Jiuhai
